INSERT {
    ?work schema:sameAs ?page;
        schema:name ?title;
    .
} WHERE {
    [] api:works ?work .
    ?work api:id ?id;
        api:title ?title;
        
        api:type ?type;
        api:score ?score;
    .

    FILTER (LCASE(?type) = "song" && xsd:integer(?score) > 90)

    BIND(IRI(concat("https://musicbrainz.org/work/", ?id)) as ?page)
}