@prefix sd:      <http://www.w3.org/ns/sparql-service-description#>.
@prefix shacl:   <http://www.w3.org/ns/shacl#>.
@prefix hydra:   <http://www.w3.org/ns/hydra/core#>.
@prefix schema:  <http://schema.org/>.
@prefix sms:     <http://ns.inria.fr/sparql-micro-service#>.

template st:start {

    format { <../tpl1_start.html> "" }

    # Generate one line for each SPARQL micro-service
    st:call-template(st:oneSms)

    format { <../tpl3_end.html> "" }

} where {}
