@prefix schema:  <http://schema.org/>.
@prefix sd:      <http://www.w3.org/ns/sparql-service-description#>.
@prefix shacl:   <http://www.w3.org/ns/shacl#>.
@prefix sms:     <http://ns.inria.fr/sparql-micro-service#>.

template st:start {

    if (?boundName = "service not found",
        st:call-template(st:not-found),
        st:call-template(st:main)
    )

} where {
    # Retrieve the service URI from the URL query string (?param=http://example.org/service)
    BIND(st:get(st:param) as ?param)
    BIND(if (bound(?param) && ?param != "", IRI(?param), IRI("<no_service>")) as ?service)

    OPTIONAL { ?service a sd:Service; schema:name ?name . }
    BIND(coalesce(?name, "service not found") as ?boundName)
}
