prefix schema: <http://schema.org/>
prefix dwc: <http://rs.tdwg.org/dwc/terms/>

SELECT ?photo ?title ?img WHERE {

    ?taxon a dwc:Taxon;
        dwc:scientificName "Delphinus delphis";
        schema:image ?photo.

    ?photo a schema:Photograph;
        schema:name ?title;
        schema:contentUrl ?img;
        schema:thumbnailUrl ?thumbnail;
        schema:mainEntityOfPage ?pageUrl;
        schema:fileFormat "image/jpeg";
        schema:author [ schema:identifier ?owner; schema:url ?authorUrl ].
}
