INSERT {
    ?audioUri a schema:AudioObject;
        schema:contentUrl ?contentUrl;
        schema:thumbnailUrl ?thumbnail;
        schema:mainEntityOfPage ?page;
        schema:author [ schema:name ?authorName ];
        .
}
WHERE {
    ?content
        api:mediaUrl ?contentUrl;
        api:thumbnailUrl ?thumbnail;
        api:specimenUrl ?page;
        api:userDisplayName ?authorName;
        api:assetId ?id;
       .

    bind (IRI(concat("http://example.org/ld/macaulaylibrary/audio/id/", ?id)) AS ?audioUri)
}