@prefix sd:      <http://www.w3.org/ns/sparql-service-description#>.
@prefix httpvoc: <http://www.w3.org/2011/http#>.

# This query template creates provenance information triples into the result grap.
# Used when the SPARQL micro-service is configured with a config.ini file.
# It is simpler than when the service is configured with a service description graph.
INSERT DATA {
    GRAPH <{graphUri}> {
        []
            a sd:Graph;
            a prov:Entity;
            prov:generatedAtTime "{date_time_sms_invocation}"^^xsd:dateTime;
            prov:wasGeneratedBy [
                a prov:Activity;
                rdfs:label "SPARQL micro-service invocation";
                prov:wasAssociatedWith [
                    a               prov:SoftwareAgent;
                    a               schema:SoftwareApplication;
                    schema:url      <{serviceUri}>;
                    foaf:homepage   <https://github.com/frmichel/sparql-micro-service/>;
                    schema:version  "{sms_version}";
                ];
                prov:used [
                    a                    prov:Entity;
                    schema:name          "Web API invocation result";
                    prov:generatedAtTime "{date_time_cachehit}"^^xsd:dateTime;
                    prov:wasGeneratedBy [
                        a                   prov:Activity;
                        schema:name         "Web API invocation";
                        httpvoc:requestUri  "{webapi_query_string}";
                    ];
                ];
            ];
            .
    }
}