# Read the inputs from the SPARQL query in case the Hydra mapping provides a hydra:propery
SELECT ?argValue WHERE {

    GRAPH <{spinQueryGraph}> {
        ?query sp:where [ sp:predicate {predicate}; sp:object ?argValue. ]
        FILTER (isLiteral(?argValue))
    }
}