@prefix sd:      <http://www.w3.org/ns/sparql-service-description#>.
@prefix hydra:   <http://www.w3.org/ns/hydra/core#>.
@prefix shacl:   <http://www.w3.org/ns/shacl#>.

# Read the service arguments from the service description graph of a SPARQL micro-service
SELECT ?name ?predicate ?shape ?csvAsMulpInvoc WHERE {

    <{serviceUri}> 
        a sd:Service;
        dct:source [ schema:potentialAction [ hydra:mapping ?mapping ] ].
        
    ?mapping hydra:variable ?name.
    
    OPTIONAL { ?mapping hydra:property ?predicate. }
    
    OPTIONAL { ?mapping shacl:sourceShape ?shape. }

    OPTIONAL { ?mapping sms:csvAsMultipleInvocations ?csvAsMulpInvoc. }
}
