@prefix sd:      <http://www.w3.org/ns/sparql-service-description#>.
@prefix hydra:   <http://www.w3.org/ns/hydra/core#>.
@prefix schema:  <http://schema.org/>.
@prefix sms:     <http://ns.inria.fr/sparql-micro-service#>.

# Read the Web API query string template and the cache experiration period 
# from the service description graph of a SPARQL micro-service
SELECT ?apiQuery ?expiresAfter WHERE {

    <{serviceUri}> 
        a sd:Service;
        dct:source [
            schema:potentialAction [ hydra:template ?apiQuery ]
        ].
        
   OPTIONAL { 
        <{serviceUri}> sms:cacheExpiresAfter ?expiresAfter.
    }
}