@prefix sp:      <http://spinrdf.org/sp#> .

# Read the inputs from the SPARQL query in case the Hydra mapping provides a hydra:property
SELECT ?argValue WHERE {

    GRAPH <{spinQueryGraph}> {
        [] sp:predicate <{predicate}>; sp:object ?argValue.
        FILTER (isLiteral(?argValue))
    }
}