prefix schema:	<http://schema.org/> .

template st:audios {
    format { <../tpl_audios.html>
        group { format { <../tpl_audio.html> ?audioPage ?audioThumbnail ?audioUrl ?audioDesc } }
    }
} where {
    ?taxon a owl:Class;
        schema:audio [
            schema:contentUrl ?audioUrl;
            schema:thumbnailUrl ?audioThumbnail;
            schema:mainEntityOfPage ?audioPage;
            schema:author ?audioAuthor;
            schema:description ?audioDesc
        ].
}
