@prefix sd:    <http://www.w3.org/ns/sparql-service-description#>.

TEMPLATE st:services(?serviceDescr) {

    "SERVICE " ?service " {" st:nl()
        st:call-template(st:service-tps, ?serviceDescr, ?service)
        st:nl()st:nl()
        st:call-template(st:service-optionals, ?serviceDescr, ?service)
    st:nl() "}" st:nl()
}
WHERE {
    GRAPH ?serviceDescr {
        ?service a sd:Service.
    }
}
