@prefix sms: <http://sms.i3s.unice.fr/terms/api/>

template st:start {

    st:call-template(st:services, ?serviceDescr)

}
where {
    # Parameter passed on the query string as "...?param=<graph uri>"
    BIND(IRI(st:get(st:param)) as ?serviceDescr)
}

@public
function sms:strRep(?x) {
    if ( isLiteral(?x), concat("\"", str(?x), "\""),
      if ( isIRI(?x), concat("<", str(?x), ">"), str(?x) )
    )
}
