@prefix sms: <http://sms.i3s.unice.fr/terms/>

template st:start {

    "INSERT {" st:nl()
    " GRAPH <{EvalFedQueryGraph}> {" st:nl()
       st:call-template(st:all-tps, ?serviceDescrGraph)
    "}}" st:nl() 
    "WHERE {" st:nl() 
    "  {}" st:nl() # empty group graph pattern as the first of a UNION of other group graph patterns
       st:call-template(st:services, ?serviceDescrGraph)
    "}"
}
where {
    # Parameter passed on the query string as "...?param=<graph uri>"
    BIND(IRI(st:get(st:param)) as ?serviceDescrGraph)
}

@public
function sms:strRep(?x) {
    if ( isLiteral(?x), concat("\"", str(?x), "\""),
      if ( isIRI(?x), concat("<", str(?x), ">"), str(?x) )
    )
}
