CONSTRUCT {
    <http://example.org/ld/taxon/{urlencode(name)}>
        a dwc:Taxon;
        schema:audio ?audioUri;

        # Reinject the service argument into the graph
        dwc:scientificName {name}.
        
    ?audioUri a schema:AudioObject;
        schema:contentUrl ?contentUrl;
        schema:thumbnailUrl ?thumbnail;
        schema:mainEntityOfPage ?page;
        schema:author ?authorName;
        schema:description ?comments;
        .
}
WHERE {
    ?content
        api:mediaUrl ?contentUrl;
        api:thumbnailUrl ?thumbnail;
        api:specimenUrl ?page;
        api:userDisplayName ?authorName;
        api:assetId ?id;
       .
    OPTIONAL { ?content api:comments ?comments }

    bind (IRI(concat("http://example.org/ld/macaulaylibrary/audio/id/", ?id)) AS ?audioUri)
}
